apiVersion: v2
name: sulfoxide-iodine
description: Helm chart to install virtual cluster on a physical cluster
type: application
version: 1.15.3
appVersion: "v0.16.3"
dependencies:
  - name: vcluster
    version: v0.16.4
    repository: https://charts.loft.sh
  - name: sulfoxide-bromine
    version: 1.2.3
    repository: oci://ghcr.io/atomicloud/sulfoxide.bromine
