apiVersion: v2
name: sulfoxide-iodine
description: Helm chart to install virtual cluster on a physical cluster
type: application
version: 1.1.1
appVersion: "v0.15.7"
dependencies:
  - name: vcluster
    version: v0.15.7
    repository: https://charts.loft.sh
