apiVersion: v2
name: sulfoxide-iodine
description: Helm chart to install virtual cluster on a physical cluster
type: application
version: 1.30.0
appVersion: "v0.19.7"
dependencies:
  - name: vcluster-k8s
    alias: vcluster
    version: v0.19.7
    repository: https://charts.loft.sh
  - name: sulfoxide-bromine
    version: 1.8.0
    condition: sulfoxide-bromine.enabled
    repository: oci://ghcr.io/atomicloud/sulfoxide.bromine
#  - name: etcd
#    repository: oci://registry-1.docker.io/bitnamicharts
#    version: 9.10.5
#    condition: etcd.enabled
