apiVersion: v2
name: sulfoxide-iodine
description: Helm chart to install virtual cluster on a physical cluster
type: application
version: 1.4.0
appVersion: "v0.16.2"
dependencies:
  - name: vcluster
    version: v0.16.2
    repository: https://charts.loft.sh
