apiVersion: v2
name: sulfoxide-iodine
description: Helm chart to install virtual cluster on a physical cluster
type: application
version: 1.6.0
appVersion: "v0.16.3"
dependencies:
  - name: vcluster
    version: v0.16.3
    repository: https://charts.loft.sh
  - name: sulfoxide-bromine
    version: 1.1.1
    repository: oci://ghcr.io/atomicloud/sulfoxide.bromine
