serviceTree:
  landscape: &landscape pichu
  cluster: &cluster opal

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

vcluster:
  labels:
    <<: *tags
  annotations:
    <<: *tags
  syncer:
    extraArgs:
      - --kube-config-context-name=pichu-opal
      - --out-kube-config-server=https://pichu.opal.kubernetes.atomi.cloud
  ingress:
    host: pichu.opal.kubernetes.atomi.cloud





