serviceTree:
  landscape: &landscape raichu
  cluster: &cluster opal

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

auth:
  remoteName: RAICHU_SULFOXIDE_SOS

datastore:
  remoteName: RAICHU_OPAL_K3S_DATASTORE_ENDPOINT

datastoreCa:
  enable: true
  remoteName: RAICHU_OPAL_K3S_DATASTORE_CA

k3sSyncToken:
  remoteName: RAICHU_K3S_TOKEN



vcluster:
  podLabels:
    <<: *tags
  podAnnotations:
    <<: *tags
  labels:
    <<: *tags
  annotations:
    <<: *tags
  syncer:
    extraArgs:
      - --kube-config-context-name=raichu-opal
      - --out-kube-config-server=https://raichu.opal.kubernetes.atomi.cloud
  ingress:
    host: raichu.opal.kubernetes.atomi.cloud
