serviceTree:
  landscape: &landscape raichu
  cluster: &cluster amber

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

auth:
  clientId: 
    remoteName: RAICHU_SULFOXIDE_SOS_CLIENT_ID
  clientSecret:
    remoteName: RAICHU_SULFOXIDE_SOS_CLIENT_SECRET

sulfoxide-bromine:
  serviceTree:
    landscape: *landscape
    cluster: *cluster

vcluster:
  replicas: 3
  coredns:
    replicas: 3
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
  etcd:
    replicas: 3
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1.5Gi
    storage:
      persistence: true
      className: ebs-gp3
    labels:
      <<: *tags
    annotations:
      <<: *tags
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
  syncer:
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi
    replicas: 3
    labels:
      <<: *tags
    annotations:
      <<: *tags
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
    extraArgs:
      - --kube-config-context-name=raichu-amber
      - --out-kube-config-server=https://raichu.amber.kubernetes.atomi.cloud
      - --sync-labels=atomi.cloud/*
  ingress:
    host: raichu.amber.kubernetes.atomi.cloud



