serviceTree:
  landscape: &landscape raichu
  cluster: &cluster onyx

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

auth:
  remoteName: RAICHU_SULFOXIDE_SOS

vcluster:
  replicas: 3
  coredns:
    replicas: 3
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
  etcd:
    replicas: 3
    storage:
      persistence: true
      className: ebs-gp3
    labels:
      <<: *tags
    annotations:
      <<: *tags
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
  syncer:
    nodeSelector:
      kubernetes.io/arch: arm64
    replicas: 3
    labels:
      <<: *tags
    annotations:
      <<: *tags
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
    extraArgs:
      - --kube-config-context-name=raichu-onyx
      - --out-kube-config-server=https://raichu.onyx.kubernetes.cluster.atomi.cloud
  plugin:
    secret-syncer:
      image: ghcr.io/kirinnee/vcluster-secret-syncer/secret-syncer-arm:main
  ingress:
    host: raichu.onyx.kubernetes.cluster.atomi.cloud



