# -- AtomiCloud Service Tree. See [ServiceTree](https://atomicloud.larksuite.com/wiki/OkfJwTXGFiMJkrk6W3RuwRrZs64?theme=DARK&contentTheme=DARK#MHw5d76uDo2tBLx86cduFQMRsBb)
serviceTree:
  platform: &platform sulfoxide
  service: &service iodine
  layer: &layer "1"

# -- Kubernetes labels and annotations, following Service Tree
tags: &tags
  atomi.cloud/platform: *platform
  atomi.cloud/service: *service
  atomi.cloud/layer: *layer

# -- Root Doppler token
auth:
  # -- external secret refresh interval
  refreshInterval: 1h
  # -- Secret store to reference
  secretStore:
    # -- name of the secret store to reference
    name: doppler
    # -- kind of the secret store to reference
    kind: ClusterSecretStore
  policy:
    # -- External Secret creation policy
    creation: Owner
    # -- External Secret deletion policy
    deletion: Retain
  # -- name of the secret to be created
  name: pichu-root-token
  # -- name of DOPPLER_TOKEN to be stored
  remoteName: PICHU_SULFOXIDE_SOS
  # -- upsync namespace
  upsyncNamespace: default
  # -- secret key to store DOPPLER_TOKEN
  secretKey: DOPPLER_TOKEN

# -- Virtual Cluster Configuration. See [vcluster documentation](https://artifacthub.io/packages/helm/loft/vcluster)
vcluster:
  labels:
    <<: *tags
  annotations:
    <<: *tags
  sync:
    configmaps:
      all: true
    secrets:
      all: true
    ingresses:
      enabled: true
  proxy:
    metricsServer:
      nodes:
        enabled: true
      pods:
        enabled: true
  syncer:
    extraArgs:
      - --tls-san=https://kubernetes.atomi.cloud
  ingress:
    enabled: true
    ingressClassName: nginx
    host: kubernetes.atomi.cloud
  telemetry:
    disabled: true
  plugin:
    secret-syncer:
      image: ghcr.io/kirinnee/vcluster-secret-syncer/secret-syncer-amd:1.0.0
      imagePullPolicy: IfNotPresent
  init:
    manifests: |
      apiVersion: v1
      kind: Namespace
      metadata:
        labels:
          kubernetes.io/metadata.name: sulfoxide
        name: sulfoxide


