serviceTree:
  landscape: &landscape pichu
  cluster: &cluster opal

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

auth:
  name: pichu-root-token
  remoteName: PICHU_SULFOXIDE_SOS
  upsyncNamespace: sulfoxide

sulfoxide-bromine:
  storeName: &storeName doppler-pichu-iodine

datastore:
  secretStore:
    name: *storeName
  name: &k3sDatastoreEndpoint pichu-datastore-endpoint
  remoteName: PICHU_K3S_DATASTORE_ENDPOINT
  secretKey: &k3sSecretKey K3S_DATASTORE_ENDPOINT

vcluster:
  vcluster:
    env:
      - name: K3S_DATASTORE_ENDPOINT
        valueFrom:
        secretKeyRef:
          name: *k3sDatastoreEndpoint
          key: *k3sSecretKey
  labels:
    <<: *tags
  annotations:
    <<: *tags
  syncer:
    extraArgs:
      - --kube-config-context-name=pichu-opal
      - --out-kube-config-server=https://pichu.opal.kubernetes.cluster.atomi.cloud
  ingress:
    host: pichu.opal.kubernetes.cluster.atomi.cloud
