serviceTree:
  landscape: &landscape pikachu
  cluster: &cluster opal

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

vcluster:
  labels:
    <<: *tags
  annotations:
    <<: *tags
  sync:
    ingresses: true
  syncer:
    extraArgs:
      - --kube-config-context-name=pikachu-opal
      - --out-kube-config-server=https://pikachu.kubernetes.atomi.cloud
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    host: pikachu.kubernetes.atomi.cloud
  telemetry:
    disabled: true





