# -- AtomiCloud Service Tree. See [ServiceTree](https://atomicloud.larksuite.com/wiki/OkfJwTXGFiMJkrk6W3RuwRrZs64?theme=DARK&contentTheme=DARK#MHw5d76uDo2tBLx86cduFQMRsBb)
serviceTree:
  platform: &platform sulfoxide
  service: &service iodine
  layer: &layer "1"

# -- Kubernetes labels and annotations, following Service Tree
tags: &tags
  atomi.cloud/platform: *platform
  atomi.cloud/service: *service
  atomi.cloud/layer: *layer

# -- Virtual Cluster Configuration. See [vcluster documentation](https://artifacthub.io/packages/helm/loft/vcluster)
vcluster:
  labels:
    <<: *tags
  annotations:
    <<: *tags
  sync:
    ingresses:
      enabled: true
  syncer:
    extraArgs:
      - --tls-san=https://kubernetes.atomi.cloud
  ingress:
    enabled: true
    ingressClassName: kong
    host: kubernetes.atomi.cloud
  telemetry:
    disabled: true





