serviceTree:
  landscape: &landscape raichu
  cluster: &cluster opal

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

vcluster:
  labels:
    <<: *tags
  annotations:
    <<: *tags
  syncer:
    extraArgs:
      - --kube-config-context-name=raichu-opal
      - --out-kube-config-server=https://raichu.kubernetes.atomi.cloud
  ingress:
    host: raichu.kubernetes.atomi.cloud





