serviceTree:
  landscape: &landscape pikachu
  cluster: &cluster ruby

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

auth:
  remoteName: PIKACHU_SULFOXIDE_SOS

datastore:
  enable: true
  remoteName: PIKACHU_RUBY_K3S_DATASTORE_ENDPOINT

vcluster:
  replicas: 1
  coredns:
    replicas: 1
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
  etcd:
    storage:
      persistence: true
    labels:
      <<: *tags
    annotations:
      <<: *tags
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
  syncer:
    labels:
      <<: *tags
    annotations:
      <<: *tags
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
    extraArgs:
      - --kube-config-context-name=pikachu-ruby
      - --out-kube-config-server=https://pikachu.ruby.kubernetes.atomi.cloud
  ingress:
    host: pikachu.ruby.kubernetes.atomi.cloud
