serviceTree:
  landscape: &landscape pichu
  cluster: &cluster onyx

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

auth:
  remoteName: PICHU_SULFOXIDE_SOS

vcluster:
  replicas: 1
  coredns:
    replicas: 1
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
  etcd:
    nodeSelector:
      topology.kubernetes.io/zone: ap-southeast-1a
    storage:
      persistence: true
      className: ebs-gp3
    labels:
      <<: *tags
    annotations:
      <<: *tags
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
  syncer:
    nodeSelector:
      kubernetes.io/arch: arm64
    labels:
      <<: *tags
    annotations:
      <<: *tags
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
    extraArgs:
      - --kube-config-context-name=pichu-onyx
      - --out-kube-config-server=https://pichu.onyx.kubernetes.atomi.cloud
      - --sync-labels=atomi.cloud/*
  plugin:
    secret-syncer:
      image: ghcr.io/kirinnee/vcluster-secret-syncer/secret-syncer-arm:main
  ingress:
    host: pichu.onyx.kubernetes.atomi.cloud

