serviceTree:
  landscape: &landscape pikachu
  cluster: &cluster opal

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

auth:
  name: pikachu-root-token
  remoteName: PIKACHU_SULFOXIDE_SOS
  upsyncNamespace: sulfoxide

sulfoxide-bromine:
  storeName: &storeName doppler-pikachu-iodine

datastore:
  secretStore:
    name: *storeName
  name: &k3sDatastoreEndpoint pikachu-datastore-endpoint
  remoteName: PIKACHU_K3S_DATASTORE_ENDPOINT
  secretKey: &k3sSecretKey K3S_DATASTORE_ENDPOINT

vcluster:
  vcluster:
    env:
      - name: K3S_DATASTORE_ENDPOINT
        valueFrom:
        secretKeyRef:
          name: *k3sDatastoreEndpoint
          key: *k3sSecretKey
  labels:
    <<: *tags
  annotations:
    <<: *tags
  syncer:
    extraArgs:
      - --kube-config-context-name=pikachu-opal
      - --out-kube-config-server=https://pikachu.opal.kubernetes.cluster.atomi.cloud
  ingress:
    host: pikachu.opal.kubernetes.cluster.atomi.cloud
