serviceTree:
  landscape: &landscape pikachu
  cluster: &cluster opal

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

auth:
  name: pikachu-root-token
  remoteName: PIKACHU_SULFOXIDE_SOS
  upsyncNamespace: sulfoxide


vcluster:
  labels:
    <<: *tags
  annotations:
    <<: *tags
  syncer:
    extraArgs:
      - --kube-config-context-name=pikachu-opal
      - --out-kube-config-server=https://pikachu.opal.kubernetes.cluster.atomi.cloud
  ingress:
    host: pikachu.opal.kubernetes.cluster.atomi.cloud





