serviceTree:
  landscape: &landscape pichu
  cluster: &cluster opal

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

auth:
  clientId:
    remoteName: PICHU_SULFOXIDE_SOS_CLIENT_ID
  clientSecret:
    remoteName: PICHU_SULFOXIDE_SOS_CLIENT_SECRET

vcluster:
  replicas: 1
  api:
    extraArgs:
      - --service-cidr=10.245.0.0/16
  coredns:
    replicas: 1
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
  etcd:
    storage:
      persistence: true
    labels:
      <<: *tags
    annotations:
      <<: *tags
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
  syncer:
    labels:
      <<: *tags
    annotations:
      <<: *tags
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
    extraArgs:
      - --kube-config-context-name=pichu-opal
      - --out-kube-config-server=https://pichu.opal.kubernetes.atomi.cloud
      - --sync-labels=atomi.cloud/*
  ingress:
    host: pichu.opal.kubernetes.atomi.cloud
