serviceTree:
  landscape: &landscape pichu
  cluster: &cluster opal

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

auth:
  name: pichu-root-token
  remoteName: PICHU_SULFOXIDE_SOS
  upsyncNamespace: sulfoxide

sulfoxide-bromine:
  storeName: &storeName doppler-pichu-iodine

vcluster:
  replicas: 1
  coredns:
    replicas: 1
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
  etcd:
    storage:
      persistence: true
    labels:
      <<: *tags
    annotations:
      <<: *tags
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
  syncer:
    labels:
      <<: *tags
    annotations:
      <<: *tags
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
    extraArgs:
      - --kube-config-context-name=pichu-opal
      - --out-kube-config-server=https://pichu.opal.kubernetes.cluster.atomi.cloud
  ingress:
    host: pichu.opal.kubernetes.cluster.atomi.cloud
