serviceTree:
  landscape: &landscape raichu
  cluster: &cluster opal

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

auth:
  remoteName: RAICHU_SULFOXIDE_SOS

vcluster:
  replicas: 3
  coredns:
    replicas: 3
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
  etcd:
    replicas: 3
    storage:
      persistence: true
    labels:
      <<: *tags
    annotations:
      <<: *tags
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
  syncer:
    replicas: 3
    labels:
      <<: *tags
    annotations:
      <<: *tags
    podAnnotations:
      <<: *tags
    podLabels:
      <<: *tags
    extraArgs:
      - --kube-config-context-name=raichu-opal
      - --out-kube-config-server=https://raichu.opal.kubernetes.atomi.cloud
  ingress:
    host: raichu.opal.kubernetes.atomi.cloud

