serviceTree:
  landscape: &landscape pichu
  cluster: &cluster ruby

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

auth:
  remoteName: PICHU_SULFOXIDE_SOS

datastore:
  enable: true
  remoteName: PICHU_RUBY_K3S_DATASTORE_ENDPOINT

datastoreCa:
  enable: true
  remoteName: PICHU_RUBY_K3S_DATASTORE_CA

k3sSyncToken:
  remoteName: PICHU_K3S_TOKEN

etcd:
  enabled: false

vcluster:
  replicas: 1
  coredns:
    replicas: 1
  podLabels:
    <<: *tags
  podAnnotations:
    <<: *tags
  labels:
    <<: *tags
  annotations:
    <<: *tags
  syncer:
    extraArgs:
      - --kube-config-context-name=pichu-ruby
      - --out-kube-config-server=https://pichu.ruby.kubernetes.atomi.cloud
  ingress:
    host: pichu.ruby.kubernetes.atomi.cloud

  volumes:
    - name: datastore-tls
      secret:
        secretName: datastore-ca
        items:
          - key: K3S_DATASTORE_CAFILE
            path: cert.ca
  vcluster:
    extraVolumeMounts:
      - mountPath: /etc/certs
        name: datastore-tls
    env:
      - name: K3S_DATASTORE_ENDPOINT
        valueFrom:
          secretKeyRef:
            name: datastore-endpoint
            key: K3S_DATASTORE_ENDPOINT
      - name: K3S_DATASTORE_CAFILE
        value: /etc/certs/cert.ca
