serviceTree:
  landscape: &landscape pichu
  cluster: &cluster opal

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

auth:
  name: pichu-root-token
  remoteName: PICHU_SULFOXIDE_SOS
  upsyncNamespace: sulfoxide


vcluster:
  labels:
    <<: *tags
  annotations:
    <<: *tags
  syncer:
    extraArgs:
      - --kube-config-context-name=pichu-opal
      - --out-kube-config-server=https://pichu.opal.kubernetes.cluster.atomi.cloud
  ingress:
    host: pichu.opal.kubernetes.cluster.atomi.cloud





