serviceTree:
  landscape: &landscape raichu
  cluster: &cluster opal

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

auth:
  clientId:
    remoteName: RAICHU_SULFOXIDE_SOS_CLIENT_ID
  clientSecret:
    remoteName: RAICHU_SULFOXIDE_SOS_CLIENT_SECRET

vcluster:
  controlPlane:
    backingStore:
      etcd:
        deploy:
          statefulSet:
            persistence:
              volumeClaim:
                enabled: true
            highAvailability:
              replicas: 3
            annotations:
              <<: *tags
            labels:
              <<: *tags
            pods:
              labels:
                <<: *tags
              annotations:
                <<: *tags
    coredns:
      deployment:
        replicas: 3
        annotations:
          <<: *tags
        labels:
          <<: *tags
        pods:
          annotations:
            <<: *tags
          labels:
            <<: *tags
    ingress:
      host: raichu.opal.kubernetes.atomi.cloud
    statefulSet:
      highAvailability:
        replicas: 3
      pods:
        labels:
          <<: *tags
        annotations:
          <<: *tags
      labels:
        <<: *tags
      annotations:
        <<: *tags
  exportKubeConfig:
    context: raichu-opal
    server: https://raichu.opal.kubernetes.atomi.cloud
