serviceTree:
  landscape: &landscape raichu
  cluster: &cluster opal

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

auth:
  name: raichu-root-token
  remoteName: RAICHU_SULFOXIDE_SOS
  upsyncNamespace: sulfoxide

vcluster:
  labels:
    <<: *tags
  annotations:
    <<: *tags
  syncer:
    extraArgs:
      - --kube-config-context-name=raichu-opal
      - --out-kube-config-server=https://raichu.opal.kubernetes.cluster.atomi.cloud
  ingress:
    host: raichu.opal.kubernetes.cluster.atomi.cloud





