serviceTree:
  landscape: &landscape pikachu
  cluster: &cluster ruby

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

auth:
  remoteName: PIKACHU_SULFOXIDE_SOS

datastore:
  remoteName: PIKACHU_RUBY_K3S_DATASTORE_ENDPOINT

datastoreCa:
  enable: true
  remoteName: PIKACHU_RUBY_K3S_DATASTORE_CA

k3sSyncToken:
  remoteName: PIKACHU_K3S_TOKEN

vcluster:
  replicas: 1
  coredns:
    replicas: 1
  podLabels:
    <<: *tags
  podAnnotations:
    <<: *tags
  labels:
    <<: *tags
  annotations:
    <<: *tags
  syncer:
    extraArgs:
      - --kube-config-context-name=pikachu-ruby
      - --out-kube-config-server=https://pikachu.ruby.kubernetes.atomi.cloud
  ingress:
    host: pikachu.ruby.kubernetes.atomi.cloud
