version: '3'

env:
  RELEASE_NAME: sulfoxide-iodine

includes:
  util: tasks/Taskfile.util.yaml
  pichu:opal:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: pichu
      CLUSTER: opal
  pikachu:opal:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: pikachu
      CLUSTER: opal
  raichu:opal:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: raichu
      CLUSTER: opal
  pichu:ruby:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: pichu
      CLUSTER: ruby
  pikachu:ruby:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: pikachu
      CLUSTER: ruby
  raichu:ruby:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: raichu
      CLUSTER: ruby
  pichu:onyx:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: pichu
      CLUSTER: onyx
  pikachu:onyx:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: pikachu
      CLUSTER: onyx
  raichu:onyx:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: raichu
      CLUSTER: onyx

tasks:
  # Utility
  start:cluster:
    desc: Starts the playground cluster to test helm charts
    cmds:
      - ./scripts/local/create-k3d-cluster.sh

  stop:cluster:
    desc: Destroys the playground cluster to test helm charts
    cmds:
      - ./scripts/local/delete-k3d-cluster.sh

  # Helm Operations
  update:
    desc: Update Helm dependencies
    dir: chart
    cmds:
      - helm dependency update

  latest:
    desc: Get the latest version of External Secrets Operator
    silent: true
    cmds:
      - task: util:latest
        vars:
          REPO_NAME: vcluster
          REPO_URL: https://charts.loft.sh
          CHART_NAME: vcluster-k8s
      - >-
        echo "sulfoxide-bromine: $(skopeo list-tags docker://ghcr.io/atomicloud/sulfoxide.bromine/sulfoxide-bromine | jq -r '.Tags[]' | sort -V | tail -n 1)"
