{{- if .Values.datastoreCa.enable }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name -}}-datastore-ca-external-secret
  annotations: {{- include "sulfoxide-iodine.annotations" . | nindent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
  labels: {{- include "sulfoxide-iodine.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.datastoreCa.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.datastoreCa.secretStore.name }}
    kind: {{ .Values.datastoreCa.secretStore.kind }}
  target:
    name: {{ .Values.datastoreCa.name }}
    creationPolicy: {{ .Values.datastoreCa.policy.creation }}
    deletionPolicy: {{ .Values.datastoreCa.policy.deletion }}
  data:
    - secretKey: "{{ .Values.datastoreCa.secretKey }}"
      remoteRef:
        key: "{{ .Values.datastoreCa.remoteName }}"
{{- end }}