apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name -}}-k3s-external-secret
  annotations: {{- include "sulfoxide-iodine.annotations" . | nindent 4 }}
    {{- toYaml .Values.secretAnnotation | nindent 4 }}
  labels: {{- include "sulfoxide-iodine.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.datastore.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.k3sSyncToken.secretStore.name }}
    kind: {{ .Values.k3sSyncToken.secretStore.kind }}
  target:
    name: {{ .Values.k3sSyncToken.name }}
    creationPolicy: {{ .Values.k3sSyncToken.policy.creation }}
    deletionPolicy: {{ .Values.k3sSyncToken.policy.deletion }}
  data:
    - secretKey: "{{ .Values.k3sSyncToken.secretKey }}"
      remoteRef:
        key: "{{ .Values.k3sSyncToken.remoteName }}"