apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name -}}-external-secret
  annotations: {{- include "sulfoxide-iodine.annotations" . | nindent 4 }}
    "secret-upsync.kirinnee.dev/enabled": "true"
    "secret-upsync.kirinnee.dev/namespace": "{{ .Values.auth.upsyncNamespace }}"
    {{- toYaml .Values.secretAnnotation | nindent 4 }}
  labels: {{- include "sulfoxide-iodine.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.auth.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.auth.secretStore.name }}
    kind: {{ .Values.auth.secretStore.kind }}
  target:
    name: {{ .Values.auth.name }}
    creationPolicy: {{ .Values.auth.policy.creation }}
    deletionPolicy: {{ .Values.auth.policy.deletion }}
  dataFrom:
    - find:
        name:
          regexp: "{{ .Values.auth.clientId.remoteName }}"
      rewrite:
        - regexp:
            source: .*
            target: "{{ .Values.auth.clientId.secretKey }}"
    - find:
        name:
          regexp: "{{ .Values.auth.clientSecret.remoteName }}"
      rewrite:
        - regexp:
            source: .*
            target: "{{ .Values.auth.clientSecret.secretKey }}"